# -*- coding: utf-8 -*-
"""Asas Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XkIGtBvjhtaCc7cvq5YaAgh89wn0T-H2
"""

print("Hello, Python!")
print("Selamat Datang ke Latihan Python")

"""#Pengenalan"""

nama = "Ali" umur = 20 tinggi = 1.7

print(nama) print(umur) print(tinggi)

"""#Pemboleh Ubah

"""

nama = input("Masukkan nama anda: ")
print("Selamat datang", nama)

umur = int(input("Masukkan umur anda: "))
print("Umur anda ialah", umur)

"""#Menerima input"""