# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ua_wrLoHdfU5F3XdPNAXgzWkbsNLbtoG
"""

df["Gred"] = df["Markah"].apply(tentukan_gred)

print(df)

"""#Langkah 11 : Baca fail CSV
data_baru = pd.read_csv

#Import library
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""#Bina array markah"""

markah = np.array([70, 85, 90, 65, 80])
print(markah)

"""#Kira purata markah"""

purata = np.mean(markah)
print("Purata markah:", purata)

"""#Cari markah tertinggi"""

tertinggi = np.max(markah)
print("Markah tertinggi:", tertinggi)

"""#Cari markah terendah"""

terendah = np.min(markah)
print("Markah terendah:", terendah)

"""#Kira jumlah keseluruhan"""

jumlah = np.sum(markah)
print("Jumlah markah:", jumlah)

"""#Tambah markah bonus

"""

markah_baru = markah + 5
print(markah_baru)

"""#Bahagian C: Amali pandas
Langkah 1: Sediakan data pelajar

"""

data = {
 "Nama": ["Ali", "Siti", "Kumar", "Mei Ling", "Aiman"],  "Markah": [70, 85, 90, 65, 80]
}

"""#Bina DataFrame

"""

df = pd.DataFrame(data)
print(df)

"""# Paparkan data teratas"""

print(df.head())

"""# Paparkan nama pelajar"""

print(df["Nama"])

"""#Paparkan markah sahaja"""

print(df["Markah"])

"""# Kira purata markah menggunakan pandas"""

purata = df["Markah"].mean()
print("Purata markah:", purata)

"""#Tapis pelajar yang mendapat markah 80 dan ke atas"""

pelajar_cemerlang = df[df["Markah"] >= 80]
print(pelajar_cemerlang)

"""#Tambah lajur status"""

df["Status"] = np.where(df["Markah"] >= 50, "Lulus", "Gagal")
print(df)

"""#Tambah lajur gred"""

def tentukan_gred(markah):
  if markah >= 80:
    return "A"
  elif markah >= 65:
    return "B"
  elif markah >= 50:
    return "C"
  else:
    return "D"
df["Gred"] = df["Markah"].apply(tentukan_gred)
print(df)

"""#Simpan data ke dalam"""

df.to_csv("markah_pelajar.csv", index=False)
print("Fail berjaya disimpan.")

"""#Baca fail CSV"""

data_baru = pd.read_csv("markah_pelajar.csv")
print(data_baru)