# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QHLyDiRyEtu0PMjlFpBzOsP9ntlDMSuT
"""

nombor1 = 10
nombor2 = 5

print(nombor1 + nombor2)
print(nombor1 - nombor2)
print(nombor1 * nombor2)
print(nombor1 / nombor2)

"""#Pernyataan Syarat"""

markah = int(input("Masukkan markah: "))

if markah >= 80:
  print("Gred A")
elif markah >= 60:
  print("Gred B")
elif markah >= 40:
  print("Gred C")
else:
  print("Gagal")

"""#Gelung for"""

for nombor in range(1, 6):
  print(nombor)

"""#Gelung while"""

nombor = 1

while nombor <= 5:
  if nombor % 2 == 0:
    print(nombor)
  nombor += 1

"""#Senarai atau list"""

buah = ["Epal", "Oren", "Mangga"]
for item in buah:
    print(item)

buah = {"Epal", "Oren", "Mangga"}

print(buah)
# Sets are unordered and do not support indexing.
# Convert to a list if you need to access elements by index.
buah_list = list(buah)
print(buah_list[0])

"""#Fungsi"""

nombor1 = float(input("Masukkan nombor pertama:"))
nombor2 = float(input("Masukkan nombor kedua:"))

jumlah = nombor1 + nombor2

print("Jumlah ialah:", jumlah)