# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15oxczy2oBLvxlPNMLAyhctuqElFGOvuz

#Semua bar menggunakan satu warna
"""

import matplotlib.pyplot as plt
nama = ["Ali", "Siti", "Kumar", "Mei Ling", "Aiman"]
markah = [70, 85, 90, 65, 80]
plt.bar(nama, markah, color="blue")
plt.title("Markah Pelajar")
plt.xlabel("Nama Pelajar")
plt.ylabel("Markah")
plt.show()

"""#Pelajar boleh menukar:"""

color="blue"

"""#kepada warna lain seperti:"""

color="red"
color="green"
color="orange"
color="purple"
color="pink"
color="yellow"

"""#Setiap bar menggunakan warna berbeza"""

import matplotlib.pyplot as plt
nama = ["Ali", "Siti", "Kumar", "Mei Ling", "Aiman"]
markah = [70, 85, 90, 65, 80]
warna = ["blue", "green", "orange", "purple", "red"]

# Senarai warna mesti mempunyai bilangan warna yang sama dengan bilangan pelajar.

# Contoh 3: Pengguna memilih warna graf
# Kod ini lebih sesuai dijadikan latihan amali kerana pelajar boleh menaip sendiri warna
# yang dikehendaki.

# Contoh input:

# Semua bar akan dipaparkan dalam warna hijau.

# Contoh 4: Ubah warna bar, bingkai dan latar belakang
plt.bar(nama, markah, color=warna)
plt.title("Markah Pelajar")
plt.xlabel("Nama Pelajar")
plt.ylabel("Markah")
plt.show()

"""#Pengguna memilih warna graf"""

import matplotlib.pyplot as plt
nama = ["Ali", "Siti", "Kumar", "Mei Ling", "Aiman"]
markah = [70, 85, 90, 65, 80]
warna_pilihan = input(
"Masukkan warna graf seperti blue, red, green atau orange: "
)
plt.bar(nama, markah, color=warna_pilihan)
plt.title("Markah Pelajar")
plt.xlabel("Nama Pelajar")
plt.ylabel("Markah")
plt.show()

"""#Ubah warna bar, bingkai dan latar belakang"""

import matplotlib.pyplot as plt

# color
# edgecolor
# linewidth

nama = ["Ali", "Siti", "Kumar", "Mei Ling", "Aiman"]
markah = [70, 85, 90, 65, 80]
plt.bar(
nama,
markah,
color="skyblue",
edgecolor="black",
linewidth=2
)
plt.title("Markah Pelajar")
plt.xlabel("Nama Pelajar")
plt.ylabel("Markah")
plt.gca().set_facecolor("lightyellow")
plt.show()

"""#Ubah warna berdasarkan markah"""

import matplotlib.pyplot as plt
nama = ["Ali", "Siti", "Kumar", "Mei Ling", "Aiman"]
markah = [70, 85, 90, 65, 80]
warna = []
for nilai in markah:
    if nilai >= 80:
        warna.append("green")
    else:
        warna.append("red")
plt.bar(nama, markah, color=warna)


plt.title("Markah Pelajar")
plt.xlabel("Nama Pelajar")
plt.ylabel("Markah")
plt.show()